### ISSUE TITLE
test: flaky replication/election_qsync_stress.test.lua test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#166]
Tarantool version:
Tarantool 2.6.0-143-g0dc72812fb
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

OS version:
1. Linux (Debian 9)
2. FreeBSD 12

Bug description:
Found 2 issues:

1. https://gitlab.com/tarantool/tarantool/-/jobs/779113169#L5139

[artifacts.zip](https://github.com/tarantool/tarantool/files/5345484/artifacts.zip)

# results file checksum: cc93d7c69c6368217634718bdf3de16c
```
[035] replication/election_qsync.test.lua             vinyl           
[035] TarantoolInpector.handle() received the following error:
[035] Traceback (most recent call last):
[035]   File "/builds/M4RrgQZ3/0/tarantool/tarantool/test-run/lib/inspector.py", line 94, in handle
[035]     result = self.parser.parse_preprocessor(line)
[035]   File "/builds/M4RrgQZ3/0/tarantool/tarantool/test-run/lib/preprocessor.py", line 73, in parse_preprocessor
[035]     return self.lua_eval(name, expr[1:-1])
[035]   File "/builds/M4RrgQZ3/0/tarantool/tarantool/test-run/lib/preprocessor.py", line 388, in lua_eval
[035]     self.servers[name].admin.reconnect()
[035] KeyError: 'election_replica0'
[035] [ fail ]
[035] 
[035] Test failed! Result content mismatch:
[035] --- replication/election_qsync.result	Thu Oct  8 00:07:13 2020
[035] +++ replication/election_qsync.reject	Thu Oct  8 04:11:02 2020
[035] @@ -102,27 +102,3 @@
[035]      old_leader_nr = new_leader_nr
[035]      old_leader = new_leader
[035]  end;
[035] - | ---
[035] - | ...
[035] -test_run:cmd('setopt delimiter ""');
[035] - | ---
[035] - | - true
[035] - | ...
[035] --- We're connected to some leader.
[035] -c.space.test:select{}
[035] - | ---
[035] - | - - [1]
[035] - |   - [2]
[035] - |   - [3]
[035] - |   - [4]
[035] - |   - [5]
[035] - |   - [6]
[035] - |   - [7]
[035] - |   - [8]
[035] - |   - [9]
[035] - |   - [10]
[035] - | ...
[035] -
[035] -test_run:drop_cluster(SERVERS)
[035] - | ---
[035] - | ...
[035] 
```

2. https://gitlab.com/tarantool/tarantool/-/jobs/779113714#L5729

[artifacts.zip](https://github.com/tarantool/tarantool/files/5345503/artifacts.zip)

# results file checksum: 3fb2e6cef4c8fa1d0edd8654fd2d8ef6
```
[021] replication/election_qsync.test.lua             vinyl           
[021] TarantoolInpector.handle() received the following error:
[021] Traceback (most recent call last):
[021]   File "/home/vagrant/tarantool/test-run/lib/inspector.py", line 94, in handle
[021]     result = self.parser.parse_preprocessor(line)
[021]   File "/home/vagrant/tarantool/test-run/lib/preprocessor.py", line 106, in parse_preprocessor
[021]     return self.server(stype, sname, options)
[021]   File "/home/vagrant/tarantool/test-run/lib/preprocessor.py", line 338, in server
[021]     return getattr(self, attr)(ctype, sname, opts)
[021]   File "/home/vagrant/tarantool/test-run/lib/preprocessor.py", line 218, in server_stop
[021]     self.connections[sname].disconnect()
[021] KeyError: 'election_replica2'
[021] [ fail ]
[021] 
[021] Test failed! Result content mismatch:
[021] --- replication/election_qsync.result	Thu Oct  8 04:07:26 2020
[021] +++ replication/election_qsync.reject	Fri May  8 08:24:37 2020
[021] @@ -103,6 +103,7 @@
[021]      old_leader = new_leader
[021]  end;
[021]   | ---
[021] + | - error: Can't modify data because this instance is in read-only mode.
[021]   | ...
[021]  test_run:cmd('setopt delimiter ""');
[021]   | ---
[021] @@ -113,16 +114,6 @@
[021]   | ---
[021]   | - - [1]
[021]   |   - [2]
[021] - |   - [3]
[021] - |   - [4]
[021] - |   - [5]
[021] - |   - [6]
[021] - |   - [7]
[021] - |   - [8]
[021] - |   - [9]
[021] - |   - [10]
[021]   | ...
[021]  
[021]  test_run:drop_cluster(SERVERS)
[021] - | ---
[021] - | ...
[021] 
```

3. https://gitlab.com/tarantool/tarantool/-/jobs/795044495#L5273

[artifacts.zip](https://github.com/tarantool/tarantool/files/5392439/artifacts.zip)

# results file checksum: 634bda94accdcdef7b1db3e14f28f445
```
[155] replication/election_qsync_stress.test.lua      memtx           
[155] TarantoolInpector.handle() received the following error:
[155] Traceback (most recent call last):
[155]   File "/builds/4BUsapPU/0/tarantool/tarantool/test-run/lib/inspector.py", line 94, in handle
[155]     result = self.parser.parse_preprocessor(line)
[155]   File "/builds/4BUsapPU/0/tarantool/tarantool/test-run/lib/preprocessor.py", line 106, in parse_preprocessor
[155]     return self.server(stype, sname, options)
[155]   File "/builds/4BUsapPU/0/tarantool/tarantool/test-run/lib/preprocessor.py", line 338, in server
[155]     return getattr(self, attr)(ctype, sname, opts)
[155]   File "/builds/4BUsapPU/0/tarantool/tarantool/test-run/lib/preprocessor.py", line 218, in server_stop
[155]     self.connections[sname].disconnect()
[155] KeyError: 'election_replica3'
[155] [ fail ]
[155] 
[155] Test failed! Result content mismatch:
[155] --- replication/election_qsync_stress.result	Fri Oct 16 11:31:28 2020
[155] +++ replication/election_qsync_stress.reject	Fri Oct 16 12:12:35 2020
[155] @@ -102,6 +102,7 @@
[155]      old_leader = new_leader
[155]  end;
[155]   | ---
[155] + | - error: Can't modify data because this instance is in read-only mode.
[155]   | ...
[155]  test_run:cmd('setopt delimiter ""');
[155]   | ---
[155] @@ -110,9 +111,7 @@
[155]  -- We're connected to some leader.
[155]  #c.space.test:select{} == 10 or require('log').error(c.space.test:select{})
[155]   | ---
[155] - | - true
[155] + | - null
[155]   | ...
[155]  
[155]  test_run:drop_cluster(SERVERS)
[155] - | ---
[155] - | ...
[155] 
```

4. 
https://gitlab.com/tarantool/tarantool/-/jobs/795376806#L5359

[artifacts.zip](https://github.com/tarantool/tarantool/files/5392768/artifacts.zip)

# results file checksum: 36bcdae426c18a60fd13025c09f197d0
```
[164] --- replication/election_qsync_stress.result	Fri Oct 16 14:39:00 2020
[164] +++ replication/election_qsync_stress.reject	Fri Oct 16 14:48:14 2020
[164] @@ -110,7 +110,7 @@
[164]  -- We're connected to some leader.
[164]  #c.space.test:select{} == 10 or require('log').error(c.space.test:select{})
[164]   | ---
[164] - | - true
[164] + | - null
[164]   | ...
[164]  
[164]  test_run:drop_cluster(SERVERS)
[164] 
```

5.
https://gitlab.com/tarantool/tarantool/-/jobs/795916093#L5738

[artifacts.zip](https://github.com/tarantool/tarantool/files/5394001/artifacts.zip)

# results file checksum: 209c865525154a91435c63850f15eca0
```
[027] --- replication/election_qsync_stress.result	Fri Oct 16 19:25:53 2020
[027] +++ replication/election_qsync_stress.reject	Fri May  8 08:23:59 2020
[027] @@ -102,6 +102,7 @@
[027]      old_leader = new_leader
[027]  end;
[027]   | ---
[027] + | - error: Found uncommitted sync transactions from other instance with id 2
[027]   | ...
[027]  test_run:cmd('setopt delimiter ""');
[027]   | ---
[027] @@ -110,9 +111,7 @@
[027]  -- We're connected to some leader.
[027]  #c.space.test:select{} == 10 or require('log').error(c.space.test:select{})
[027]   | ---
[027] - | - true
[027] + | - null
[027]   | ...
[027]  
[027]  test_run:drop_cluster(SERVERS)
[027] - | ---
[027] - | ...
[027] 
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by sergepetrenko** [comment]
I've ran `election_qsync_stress` for quite some time, but couldn't reproduce the election hang that @sergos mentioned.

The [ER_READONLY](https://github.com/tarantool/tarantool-qa/issues/166#issuecomment-1100304845) error was fixed recently in scope of  tarantool/tarantool#6966

It seems that the case with infinite elections is caused by `replica3`'s applier failing with `ER_INVVALID_MSGPACK`. This explains why two instances may enter the infinite election loop. replica3 doesn't receive vote requests from replica2 (its applier is dead), so replica2 never receives 2 votes. At the same time, replica3 never receives votes for itself from replica2, so replica3 never receives 2 votes. This results in infinite elections.

What causes the `ER_INVALID_MSGPACK` is a mystery though. It was fixed in scope of tarantool/tarantool#4040, so this might be another incarnation of this bug.
@sergos, could you please set `log_level=6` in `election_replica.lua` and try to reproduce this once again? With `log_level=6` replica will dump the malformed row once ER_INVALID_MSGPACK occurs. This will give us a chance to understand what's causing the error.

**Comment by sergos** [comment]
I've got the error, but not the infinite elections. The reason surprises me: it's in relay, not applier:
```
2022-04-26 11:26:13.548 [53611] main/138/main I> set 'replication_synchro_timeout' configuration option to 1000
2022-04-26 11:26:13.717 [53611] main/113/main I> subscribed replica 38acc283-910b-40db-8ecc-e5ab45764352 at fd 23, aka unix/:(socket), peer of unix/:(socket)
2022-04-26 11:26:13.717 [53611] main/113/main I> remote vclock {1: 9} local vclock {0: 2, 1: 9, 3: 2}
2022-04-26 11:26:13.718 [53611] relay/unix/:(socket)/101/main I> recover from `/workspaces/t.sergos/test/var/027_replication/election_replica2/00000000000000000005.xlog'
2022-04-26 11:26:13.718 [53611] relay/unix/:(socket)/102/main:reader V> Got a corrupted row:
2022-04-26 11:26:13.718 [53611] relay/unix/:(socket)/102/main:reader V> 00000000: 81 00 00 81 26 81 01 09 03 01
2022-04-26 11:26:13.719 [53611] relay/unix/:(socket)/101/main xrow.c:229 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
2022-04-26 11:26:13.719 [53611] relay/unix/:(socket)/101/main I> exiting the relay loop
2022-04-26 11:26:13.761 [53611] main/114/applier/unix/:/workspaces/t.sergos/test/var/027_replication/election_replica1.sock I> subscribed
2022-04-26 11:26:13.761 [53611] main/114/applier/unix/:/workspaces/t.sergos/test/var/027_replication/election_replica1.sock I> remote vclock {1: 9, 3: 2} local vclock {0: 2, 1: 9, 3: 2}
2022-04-26 11:26:13.761 [53611] main/114/applier/unix/:/workspaces/t.sergos/test/var/027_replication/election_replica1.sock I> RAFT: message {term: 3, leader: 3, leader is seen: true, state: follower} from 1
```
unfortunately, the xlog file is missing, even after I removed the test from the fragile list.
I run tests on the `dev1` box under ubuntu docker, using a `bind` mount type
```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/s.ostanevich/workspaces",
                "Destination": "/workspaces",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
``` 
I will try to reproduce without docker.

**Comment by sergepetrenko** [comment]
> The reason surprises me: it's in relay, not applier:

Wow, that's something already. Will take a look.

**Comment by sergos** [comment]
Reproduced on plain el7. 
```
2022-04-26 17:32:05.853 [36183] main/113/main I> subscribed replica 92a2b565-790f-4a2c-aa4e-2264a93a1d8e at fd 29, aka unix/:(socket), peer of unix/:(socket)
2022-04-26 17:32:05.854 [36183] main/113/main I> remote vclock {1: 5} local vclock {0: 1, 1: 5}
>>>> 2022-04-26 17:32:05.857 [36183] relay/unix/:(socket)/101/main I> recover from `/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica2/00000000000000000004.xlog'
2022-04-26 17:32:05.866 [36183] main/127/main I> subscribed replica 70f0ed78-3d15-4bcc-9fd0-87ec1ba7ea20 at fd 31, aka unix/:(socket), peer of unix/:(socket)
2022-04-26 17:32:05.866 [36183] main/127/main I> remote vclock {1: 5} local vclock {0: 1, 1: 5}
2022-04-26 17:32:05.866 [36183] main/127/main I> RAFT: fencing resumed
2022-04-26 17:32:05.867 [36183] main/106/gc I> wal/engine cleanup is resumed
>>>> 2022-04-26 17:32:05.868 [36183] relay/unix/:(socket)/101/main I> recover from `/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica2/00000000000000000004.xlog'
2022-04-26 17:32:05.911 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> subscribed
2022-04-26 17:32:05.911 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> remote vclock {1: 5} local vclock {0: 1, 1: 5}
2022-04-26 17:32:05.912 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 2, leader: 1, leader is seen: true, state: follower} from 3
2022-04-26 17:32:05.914 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 2, leader: 1, leader is seen: true, state: follower} from 3
2022-04-26 17:32:05.914 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> leaving orphan mode
2022-04-26 17:32:07.011 [36183] main/115/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica1.sock I> can't read row
2022-04-26 17:32:07.011 [36183] main/115/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica1.sock coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 25, aka unix/:(socket), peer of unix/:(socket): Broken pipe
2022-04-26 17:32:07.011 [36183] main/115/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica1.sock I> will retry every 0.10 second
>>>> 2022-04-26 17:32:07.011 [36183] relay/unix/:(socket)/101/main coio.c:349 E> SocketError: unexpected EOF when reading from socket, called on fd 31, aka unix/:(socket), peer of unix/:(socket): Broken pipe
2022-04-26 17:32:07.011 [36183] relay/unix/:(socket)/101/main I> exiting the relay loop
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 2, leader: 1, state: follower} from 3
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: begin new election round
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: bump term to 3, follow
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: vote for 2, follow
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 3, vote: 3, state: candidate, vclock: {1: 9}} from 3
2022-04-26 17:32:07.353 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: vote request is skipped - already voted in this term
2022-04-26 17:32:07.353 [36183] main/118/raft_worker I> RAFT: persisted state {term: 3, vote: 2}
2022-04-26 17:32:07.353 [36183] main/118/raft_worker I> RAFT: enter candidate state with 1 self vote
2022-04-26 17:32:07.766 [36183] main I> RAFT: begin new election round
2022-04-26 17:32:07.766 [36183] main I> RAFT: bump term to 4, follow
2022-04-26 17:32:07.766 [36183] main I> RAFT: vote for 2, follow
2022-04-26 17:32:07.766 [36183] main/118/raft_worker I> RAFT: persisted state {term: 4, vote: 2}
2022-04-26 17:32:07.766 [36183] main/118/raft_worker I> RAFT: enter candidate state with 1 self vote
2022-04-26 17:32:07.767 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 4, vote: 2, state: follower} from 3
2022-04-26 17:32:07.767 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: enter leader state with quorum 2
>>>> 2022-04-26 17:32:07.767 [36183] relay/unix/:(socket)/102/main:reader V> Got a corrupted row:
2022-04-26 17:32:07.767 [36183] relay/unix/:(socket)/102/main:reader V> 00000000: 81 00 00 81 26 81 01 09 02 01
2022-04-26 17:32:07.767 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: message {term: 4, vote: 2, leader: 2, leader is seen: true, state: follower} from 3
2022-04-26 17:32:07.767 [36183] main/117/applier/unix/:/export/s.ostanevich/workspaces/t.sergos2/test/var/029_replication/election_replica3.sock I> RAFT: vote request is skipped - the leader is already known - 2
>>>> 2022-04-26 17:32:07.767 [36183] relay/unix/:(socket)/101/main xrow.c:229 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
2022-04-26 17:32:07.767 [36183] relay/unix/:(socket)/101/main I> exiting the relay loop
```

**Comment by sergepetrenko** [comment]
Found the issue together with @sergos:
tarantool/tarantool#7089

**Comment by sergepetrenko** [comment]
Seems like we've fixed all the known issues with this test. No failures on my machine after a 1000 runs.
Closing.
